### ISSUE TITLE
你好，可以针对没有使用过npm的新手出一个教程吗？

### ISSUE THREAD

**Issue by NasserGo-zz** [chenz24/vue-blu#10]
十分抱歉的提出这个需求，我是一个想要入门的新手。
看到您的前端框架，十分想要体验一下。 但是以前没有使用过npm之类的东西。
看不懂您写的Quick Start。
不知道该在什么地方import 。  
还望不吝赐教。

**Comment by chenz24** [comment]
我简单说下吧
首先你电脑上需要安装nodejs，安装后应该也就有npm了(新版nodejs集成了npm)，然后可以按下面步骤来
1.安装[vue-cli](https://github.com/vuejs/vue-cli)(vuejs的一个脚手架工具)，具体安装方法官方有说明
2.用vue-cli初始化一个webpack项目。完成后，执行 `npm install` 安装依赖
3.`npm install vue-blu --save ` 安装vue-blu
以上都安装好后，在项目的入口文件(一般是main.js)里 添加 quick start 里说明的那些代码即：
```
import Vue from 'vue'
import VueBlu from 'vue-blu'
import 'vue-blu/dist/css/vue-blu.min.css'

Vue.use(VueBlu)
```
这样就把vue-blu安装好了，之后的就是在页面上使用各种组件了。
代码部分，你可以参考一下这个项目的docs目录里的部分。

后续，我计划做一个脚手架的项目，可以让大家更方便、开箱即用的那种
