### ISSUE TITLE
这个项目会不会一直维护下去呢？

### ISSUE THREAD

**Issue by qiaolin-pan** [chenz24/vue-blu#11]
你好，vue-blu很漂亮，小伙伴儿们看了也都挺喜欢！
冒昧的问一下，这个项目目前就你一个人在维护吗？会不会一直维护下去呢？

**Comment by chenz24** [comment]
目前是我一个人在维护，会一直维护下去的

这周刚刚发布了第一个公开版，有些组件我还在开发中，后续肯定还会更好，请保持关注，能多拉些小伙伴来关注、star就更好了 ^_^

**Comment by atricfox** [comment]
停更一年了都，估计不会再更新了，慎用！
