### ISSUE TITLE
dropdown下拉菜单无法设置跳转链接

### ISSUE THREAD

**Issue by qiaolin-pan** [chenz24/vue-blu#13]
如图：

![image](https://cloud.githubusercontent.com/assets/13342613/22172565/740d1426-dfe5-11e6-8082-41fc023037b5.png)

请问如何设置跳转链接

**Comment by chenz24** [comment]
下拉菜单是配合menu组件实现的，所以这里参见[menu](https://chenz24.github.io/vue-blu/#/components/menu) 的文档，即设置 `to`参数, 如`<menu-item icon="user" to="/components/menu/submenu2">Members</menu-item>`

**Comment by qiaolin-pan** [comment]
顺带请教一下大神，我用的laravel的gulp，在自定义主题部分需要import  'xxx.scss'，于是报这个错误“You may need an appropriate loader to handle this file type.”。请问如何指定加载器呢？
![image](https://cloud.githubusercontent.com/assets/13342613/22174318/4f9083e0-e016-11e6-8779-2f71d3f92704.png)
![image](https://cloud.githubusercontent.com/assets/13342613/22174319/5ebf21e6-e016-11e6-8ab7-1ef2f776455a.png)
![image](https://cloud.githubusercontent.com/assets/13342613/22174321/74a18850-e016-11e6-8f2c-d1b7808e1fa4.png)

**Comment by chenz24** [comment]
你可以看下 [laravel-elixir-vue-2 ](https://github.com/vuejs/laravel-elixir-vue-2) 的文档，这个插件支持在根目录添加`webpack.config.js `来作为webpack的配置。

你可以试一下，等我有时间我会写个laravel配置webpack的小教程

**Comment by qiaolin-pan** [comment]
嗯，多谢大神 ^_^
