### ISSUE TITLE
InputNumber field does concatenation

### ISSUE THREAD

**Issue by Youdaman** [chenz24/vue-blu#14]
If I type a number in an InputNumber field and hit "+" it concatenates the 1, eg enter 5, hit "+" button, field shows 51 not 6. Likewise hitting "-" shows "5-1".

Need to convert input value to integer first :)

**Comment by chenz24** [comment]
Thank you for the feedback,I'll fix this bug

**Comment by Youdaman** [comment]
I didn't explain properly. On mobile (I'm using Android) the InputNumber fields allow you to type in them, and if you do, and then hit "+", it concatenates 1s. I've attached some screenshots to show:

![screengrab-1485135967814](https://cloud.githubusercontent.com/assets/287330/22189487/f3162f00-e170-11e6-80c9-fd46e0b4e5d5.png)
![screengrab-1485135996822](https://cloud.githubusercontent.com/assets/287330/22189488/f319004a-e170-11e6-9f28-82ea1dd8485c.png)
![screengrab-1485136014925](https://cloud.githubusercontent.com/assets/287330/22189489/f31a16b0-e170-11e6-9c71-d7ef83fd91f5.png)

**Comment by chenz24** [comment]
The document was updated,try again

**Comment by Youdaman** [comment]
Thanks, that fixed the bug with numbers.

If the user enters a letter by mistake (or types the word "five" for whatever reason) it doesn't work. Maybe make it revert to the default if a non-numeric value is input.

**Comment by chenz24** [comment]
Yes, the situation should be considered.  I've improved the logic and updated the documentation.
