### ISSUE TITLE
demo和文档没有完整的vue写法

### ISSUE THREAD

**Issue by youpengfei** [chenz24/vue-blu#17]
如题。
还有能不能再vue-admin中直接集成呢？

**Comment by chenz24** [comment]
你可以参考docs里面的代码，里面有写法。
用vue-blu就可以搭出vue-admin那种界面，不算麻烦，建议看下vue-blu和bulma的文档。

**Comment by youpengfei** [comment]
@chenz24 我的意思是说现在的文档里面只有template部分吧，script部分没有，一些事件不知道怎么写，虽然查文档可以做出来，但是这个组件的推广是不是就有难度了，如果我给我小伙伴们介绍，我还要给他们写demo而不是把你的文档地址直接给他们。

**Comment by chenz24** [comment]
Got, 文档的部分我完善下，应该是有些有script的部分有些没有。另外我会抽时间写点demo类的东西供大家参考

**Comment by youpengfei** [comment]
@chenz24  多谢
