### ISSUE TITLE
vue-blu.min.css文件好像跟vue-admin的css有冲突

### ISSUE THREAD

**Issue by youpengfei** [chenz24/vue-blu#18]
在  'vue-blu/dist/css/vue-blu.min.css'
加入前
![image](https://cloud.githubusercontent.com/assets/2201746/22235264/7351e9ca-e239-11e6-9605-84e653de2f3f.png)

加入后
![image](https://cloud.githubusercontent.com/assets/2201746/22235229/3d2a9978-e239-11e6-91ee-74b918288821.png)

**Comment by chenz24** [comment]
都用了bulma的css，肯定会冲突。不建议在使用vue-blu的时候再使用vue-admin。你如果想要一个vue-admin那种后台管理系统的布局，你可以参考vue-admin写一下，只是布局的问题，工作量不大。如果你想用vue-admin里的组件，也不需要引入vue-admin，因为vue-admin的组件也是引入的vue-bulma的。你可以单独引入
