### ISSUE TITLE
Directly including vue-blu.js

### ISSUE THREAD

**Issue by ecmel** [chenz24/vue-blu#19]
I included vue-blu.js and:

```
Vue.use(window["vue-blu"]);
```
I got Uncaught TypeError: a.apply is not a function

**Comment by chenz24** [comment]
Yes, currently the problem indeed exists when including vue-blu.js directly. I've found the solution, it will be fixed soon. thanks for the feedback

**Comment by chenz24** [comment]
now, it's ok. demo: http://jsbin.com/futiro/edit?html,output
