### ISSUE TITLE
props没同步修改

### ISSUE THREAD

**Issue by Galen-Yip** [chenz24/vue-blu#21]
看了下源码 比如`pagination`
```
watch: {
    current(val) {
      if (val !== this.interCurrent) {
        this.handleChangePage(val);
      }
    }
}
```

`current`修改的时候，会触发`handleChangePage`
但是 因为interCurrent修改的时候，没有同步修改传进来的prop current，所以可能watch的current并不一定会被触发。
打个比方，一开始current传进来的时候是`1`，点击页码变成第2页，即interCurrent被修改成了2，此时，如果在父级去设置`this.current=1`，这时候，`pagination`就不工作了，因为一直都是`1`

vue组件化主张的应该是不去修改props的，1.x版本有`.sync`被废除了，额。。。。觉得越来越别扭

**Comment by chenz24** [comment]
可以用 `change ` 回调同步改变一下current
