### ISSUE TITLE
 Menu的click事件如何获取循环的当前对象

### ISSUE THREAD

**Issue by QianWenW** [chenz24/vue-blu#22]
`<menu-item v-for="page in sidebarPages"  :click="changePage">
							<span>{{page.name}}</span>
						</menu-item>`执行changpage事件的时候如果获取page

**Comment by chenz24** [comment]
可以用bind来获取
```
<menu-item v-for="page in pages" :click="changePage.bind(this, page)"> 
   <span>{{ page.name }}</span> 
</menu-item>
```
