### ISSUE TITLE
pagination pageSize

### ISSUE THREAD

**Issue by Youdaman** [chenz24/vue-blu#24]
When the page size changes in the demo, "pageSize 50" etc is output in teh console. How do I turn this off?

Also, if a user is showing 10 per page, then goes to the last page, but then chooses to show 50 per page, the current page property should change to the last possible page. e.g. if I have 15 items and I'm showing 10 per page, and my current page is page 2, when I chose to show 20 per page nothing shows because I am still on page 2. Instead, pagination.current should reset to 1 because that's the last possible page I can be on.

I was going to set this myself in the callback but didn't know how to access the private page-size attribute (that gets printed to the console) if I'm using a computed pagination object.

**Comment by chenz24** [comment]
I will add a callback when the pageSize is changing(like Function(current, pageSize)), the question in  the second paragraph is a bug, I'll fix it. But I didn't find any word printed in the console(like 'pageSize 50'), could you explain it in more detail?

**Comment by Youdaman** [comment]
In vue-blu.min.js: `handlePageSizeChange:function(t,e){console.log("pageSize",e)`
