### ISSUE TITLE
@change function for Checkbox(group) not working

### ISSUE THREAD

**Issue by mindbits** [chenz24/vue-blu#25]
Hello, 

I am a bit confused on how to call the change function for checkboxes:

I expected something like this: 

`<checkbox val="Kobe" @change="changeFunction">Kobe</checkbox>`

But the call always goes to the  _default function of the change properties instead of the "changeFunction"? So now we are using watch on the array and trigger changeFunction from there but I guess that this is not the intended behavior?

Besides this, wonderful work and I would love to see you on patreon.

**Comment by chenz24** [comment]
Hi, It would be like this  
```
<checkbox val="Kobe" :change="changeFunction">Kobe</checkbox>
```
see this demo : http://jsbin.com/nuxibavike/edit?html,output

Thanks for your kind words! I will make this project better.  😁

**Comment by mindbits** [comment]
oh thank you!

**Comment by mindbits** [comment]
Sorry to reopen this. 

While it works fine for single checkboxes it does not for a group? 

http://jsbin.com/zakupikoca/edit?html,output

**Comment by chenz24** [comment]
Sorry about this，the name of the parameter makes people confused. It's `on-change`. I will improve this.
http://jsbin.com/nekefufisa/edit?html,output
