### ISSUE TITLE
Can't use simple list inside a tab

### ISSUE THREAD

**Issue by alexander-feil** [chenz24/vue-blu#26]
Hey,

at the moment it isn't possible to use a simple list inside a tab.

```
  <ul>
    <li>Foo</li>
    <li>Bar</li>
  </ul>
```

Perhaps you could use `div` Elements for the structure instead of ul/li.

What do you think?

Bye,
Alexander

**Comment by chenz24** [comment]
Yes, It is affected by the css of tab, I'll find a better way to fix the problem. Right now, you can override the css of ul inside the tab.
