### ISSUE TITLE
Aside footer buttons

### ISSUE THREAD

**Issue by Youdaman** [chenz24/vue-blu#27]
Re https://chenz24.github.io/vue-blu/#/components/aside

Is there a way to specify a callback for the footer buttons on the aside component?

Clicking "OK" or "Cancel" both close the aside and there's no documentation for calling extra functions.

**Comment by chenz24** [comment]
It's the same as modal. so you can refer to the documentation of modal

demo: http://jsbin.com/mebogaziso/edit?html,output
