### ISSUE TITLE
希望能实现表单验证功能

### ISSUE THREAD

**Issue by danielmlc** [chenz24/vue-blu#28]
form表单中能实现表单验证功能吗

**Comment by qmdx** [comment]
验证可以参考：https://validator.niceue.com
## 真的很好的 UI 库， 希望作者坚持下去！！
@chenz24

**Comment by chenz24** [comment]
@danielmlc @qmdx  目前form表单还没有验证功能，可以配合其他第三方插件来做。验证肯定是一个重要的部分，计划中是要做的。近期比较忙，所以只是一些小的更新，忙过这段希望会有一波大更新。

感谢支持！会继续做好
