### ISSUE TITLE
你好，问一下你的notify或者modal这样的全局组件是怎么写的？

### ISSUE THREAD

**Issue by jsm1003** [chenz24/vue-blu#3]
需要用到什么知识点？能详细说一下吗？

**Comment by chenz24** [comment]
可以看下notify组件的[源码](https://github.com/chenz24/vue-blu/blob/master/src/components/notify/index.js)
大体是写一个方法，这个方法可以new出notify component。然后将这个方法注册到Vue的prototype里。
需要了解的知识点是js的`prototype`

**Comment by jsm1003** [comment]
我可以加一下你的微信问一下别的问题吗？

**Comment by chenz24** [comment]
可以，号是bluewind8606
