### ISSUE TITLE
When i try to import the sass from 'vue-blu/src/scss/main.scss' it fails for unexpected @character

### ISSUE THREAD

**Issue by D3m1urg0** [chenz24/vue-blu#33]
if i have in my main.js

import 'vue-blu/src/scss/main.scss'

webpack answers this:
> Module parse failed: C:\Users\pietro.caruso\Desktop\archi-suite\node_modules\vue-blu\src\scss\main.scss Unexpected character '@' (8:0)
> You may need an appropriate loader to handle this file type.

i am using the webpack-simple config with sass enabled

**Comment by chenz24** [comment]
I think there may be a mistake in your configuration of webpack.
