### ISSUE TITLE
table表格引入分页组件后layout不生效

### ISSUE THREAD

**Issue by duanzonglong** [chenz24/vue-blu#36]
win10

code

const data = [{'id': 1, 'work_no': '23-4608596', 'given_name': '哲恒', 'family_name': '鲁', 'name': '鲁哲恒', 'birthday': '1986-03-24', 'email': 'landrews0@storify.com', 'gender': 'Male', 'achievement': 81.0, 'remark': 'bibendum imperdiet nullam orci pede'}]
export default {
  components: {
    Xcontent
  },
  data () {
    return {
      data: data
    }
  },
  computed: {
    pagination () {
      return {
        total: this.data.length,
        layout: 'total, pager'
      }
    }
  }
}

**Comment by chenz24** [comment]
抱歉，最近比较忙。这个地方会完善一下

**Comment by 408796571** [comment]
@chenz24 Is this fixed?
