### ISSUE TITLE
希望能增加几个布局容器组件

### ISSUE THREAD

**Issue by xianzhi0520** [chenz24/vue-blu#42]
例如:目前我想实现类似于方框形的那个tab,不论多少tab,中间是等分的的宽度
layout里面的12等分布局,在mobile下不论怎样都会每行一个块级显示
多媒体组件没有:例如卡片组件,单纯构建一个图文卡片,这个很有用
列表list目前也是没有看到

**Comment by chenz24** [comment]
这个组件库是结合 bulma 这个 css 库搞的。你可以参考下 bulma 的文档。卡片组件之类的暂时还没有，以后会加上。

关于布局的方面，不建议用组件的形式做，css 的方式最合适也最灵活。建议在使用这个库的时候，先阅读下 bulma css 的文档。在布局方面和一些 html 样式、组件会有很多帮助。
