### ISSUE TITLE
Using Bulma

### ISSUE THREAD

**Issue by rfberaldo** [chenz24/vue-blu#49]
Can I use my current Bulma variables (colors, font-family, etc) to work on vue-blu? How?

**Comment by chenz24** [comment]
Yes you can, refer to https://chenz24.github.io/vue-blu/#/en/customize

**Comment by rfberaldo** [comment]
Thanks! Probably going to use it on the project I'm working in. Hope you have some time to finish the translations ;)

**Comment by Mark-Brightcloud** [comment]
@chenz24 could you explain more on step 1 "Set the sass variables and import the entry file of the library"?

**Comment by 408796571** [comment]
@chenz24 I noticed vue-blue font is smaller. I prefer bigger text from bulma. How can I go about sticking with default bulma font?
