### ISSUE TITLE
InputNumber list re-render on splice

### ISSUE THREAD

**Issue by Youdaman** [chenz24/vue-blu#53]
I have a list of values I'm using InputNumber to display, along with an up/down arrow next to each to move them up and down in the list using a splice operation. With a normal field the values move up and down but with InputNumber the fields don't refresh when the v-for list is mutated with splice.

**Comment by chenz24** [comment]
Did you add `key` to the items in `v-for`?

**Comment by Youdaman** [comment]
No I didn't, thanks!
