### ISSUE TITLE
内置的Bulma样式与bulma官网的最新样式一起用的时候，样式有冲突

### ISSUE THREAD

**Issue by nqdy666** [chenz24/vue-blu#6]
内置的Bulma样式与bulma官网的最新样式一起用的时候，样式有冲突
内置是v0.2.3版本，最新是v0.3.1 版本。

样式就冲突了

**Comment by chenz24** [comment]
试了下bulma的新版，有几处和v0.2.3不兼容的地方，不过改动也不是很大。bulma的新版才发布3天，等稳定下blu会跟进

**Comment by nqdy666** [comment]
@chenz24 新版的blu什么时候会发布哇？

**Comment by nqdy666** [comment]
@chenz24 建议用户引入的其他bluma.css不会影响组件内部的样式。

**Comment by chenz24** [comment]
blu新版发布估计会是一到两周的时间吧。意见会参考，Thx

**Comment by terranc** [comment]
有进展了吗？

**Comment by chenz24** [comment]
抱歉，最近有其他事过于繁忙，暂时无暇顾及这个库的维护了。我会忙完这段后继续更新维护。感谢支持

**Comment by terranc** [comment]
@chenz24 幸苦幸苦
