### ISSUE TITLE
请问Notify可以手动关闭吗

### ISSUE THREAD

**Issue by czs0x55aa** [chenz24/vue-blu#72]
比如我在加载数据的时候使用了Notify，数据加载完后想手动close，而不是定时

**Comment by chenz24** [comment]
可以，把 `duration ` 设置为0

**Comment by czs0x55aa** [comment]
感谢你的解答
恕我愚钝，尝试去调整duration 没有成功...
看了源码中的实现是在mounted中设置setTimeout来关闭的，所以主动关闭需要再次触发这个mounted？
不过看到组件里提供了close方法....目前凑合着这么做来主动关闭了...
this.myNotify = this.$notify.open({content: '命令执行中...', type: 'loading'});
this.myNotify.close()
