### ISSUE TITLE
scss error

### ISSUE THREAD

**Issue by Youdaman** [chenz24/vue-blu#8]
Re https://chenz24.github.io/vue-blu/?ref=madewithvuejs#/customize

node_modules\vue-blu\src\scss\elements\progressbar.scss has an undefined $font variable

I can fix this my setting $font in my variables.scss but it might be an idea to set a default :)

Also I noticed that if I use scss my fonts/colours look like the Bulma defaults, but if I import the dist css it looks like the Vue Blu site. It might be nicer for users to use the default Bulma styles for the dist css :)

**Comment by chenz24** [comment]
Thx, this is a bug,I will set a default value for`$font`.

The second point, If you want to customize vue-blu you can import your own variables.scss,set the color or font that you like and compile it, then you got your own theme.If you don't need customization,you use dist css,this is the default theme of vue-blu
