### ISSUE TITLE
一点疑问

### ISSUE THREAD

**Issue by whatwg6** [chenz24/vue-blu#91]
在知乎专栏饿了么文章看见的你  [element](https://zhuanlan.zhihu.com/p/22355579) ，
这里什么时候用到lerna 呀。

**Comment by chenz24** [comment]
这阶段加班严重，事情比较多。估计月末开始恢复维护，lerna到时候会考虑引入哈

**Comment by yxuecheng** [comment]
因为我也想做个类似的组件库，但是不上传到npm，仅仅上传到自己的rep，也想使用lerna，现在在考虑开发的时候packages 文件夹里的每个组件是否都需要webpack.config文件用来打包
