### ISSUE TITLE
问一下你的这个文档系统用的是什么呢？

### ISSUE THREAD

**Issue by Veitor** [chenz24/vue-blu#92]
能否推荐一下

**Comment by whatwg6** [comment]
参考https://juejin.im/entry/57eb1125c4c971005f87053e

**Comment by chenz24** [comment]
楼上的链接正解，是写了webpack 的 markdown loader 来实现的

**Comment by yxuecheng** [comment]
还有个问题啊，文档里面，代码可以展开收起，这个是怎么回事？md转成vue文件 自动带的功能？
