### ISSUE TITLE
How to import single component?

### ISSUE THREAD

**Issue by red010182** [chenz24/vue-blu#98]
Can I just import components I want instead of all of them?

```
import { Popover } from 'vue-blu'
export default {
	components: {
		'popover': Popover
	}
        ...
}
```

Seems doesn't work.

**Comment by youandmeonly** [comment]
is this issue solved ?

**Comment by NicoCoco1163** [comment]
> is this issue solved ?

Try this, import MYCOMP from 'vue-blu/src/components/MYCOMP'
Check the file under 'vue-blu/src/index.js'
